services:
  printmqttify:
    image: printmqttify
    container_name: printmqttify_container
    privileged: true
    ports:
      - "${CUPS_PORT:-1631}:631"
      - "${WEB_PORT:-8880}:8080"
    devices:
      - "${PRINTER_DEVICE}:${PRINTER_DEVICE}"
    volumes:
      - "${DRIVERS_PATH}:/drivers/custom"
      - ./cups_config:/etc/cups
      # Required for Avahi/mDNS to work properly
      - /var/run/dbus:/var/run/dbus
    environment:
      - HA_DISCOVERY=${HA_DISCOVERY}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    stdin_open: true
    tty: true